version = 0.1
[default.deploy.parameters]
stack_name = "PredictInjuryStack"
resolve_s3 = true
s3_prefix = "PredictInjuryStack"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
